################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../CycloneTcp/cyclone_tcp/drivers/mac/a2fxxxm3_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/am335x_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/aps3_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/avr32_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/efm32gg11_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/esp32_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/f28m35x_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/fm3_eth1_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/fm3_eth2_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/fm4_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/gd32f307_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/lm3s_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/lpc175x_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/lpc176x_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/lpc178x_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/lpc18xx_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/lpc23xx_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/lpc43xx_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/lpc54xxx_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/m2sxxx_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/m487_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/mcf5225x_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/mcimx6ul_eth1_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/mcimx6ul_eth2_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1020_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1050_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1060_eth1_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1060_eth2_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1170_eth1_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1170_eth2_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/mk6x_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/mk7x_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/mkv5x_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/mpc57xx_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/mpfsxxx_eth1_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/mpfsxxx_eth2_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/msp432e4_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/nuc472_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/omapl138_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/pic32mx_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/pic32mz_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/ra6_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/rx62n_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/rx63n_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/rza1_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/s32k148_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/s5d9_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/s7g2_eth1_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/s7g2_eth2_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/sam3x_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/sam4e_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/sam7x_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/sam9263_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/sama5d2_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/sama5d3_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/sama5d3_geth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/same54_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/same70_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/samv71_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/stm32f1xx_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/stm32f2xx_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/stm32f4xx_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/stm32f7xx_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/stm32h7xx_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/stm32mp1xx_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/str912_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/tc2xx_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/tc3xx_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/tm4c129_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/tms570_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/xmc4400_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/xmc4500_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/xmc4700_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/xmc4800_eth_driver.c \
../CycloneTcp/cyclone_tcp/drivers/mac/zynq7000_eth_driver.c 

OBJS += \
./CycloneTcp/cyclone_tcp/drivers/mac/a2fxxxm3_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/am335x_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/aps3_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/avr32_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/efm32gg11_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/esp32_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/f28m35x_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/fm3_eth1_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/fm3_eth2_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/fm4_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/gd32f307_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/lm3s_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/lpc175x_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/lpc176x_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/lpc178x_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/lpc18xx_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/lpc23xx_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/lpc43xx_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/lpc54xxx_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/m2sxxx_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/m487_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/mcf5225x_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/mcimx6ul_eth1_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/mcimx6ul_eth2_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1020_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1050_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1060_eth1_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1060_eth2_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1170_eth1_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1170_eth2_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/mk6x_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/mk7x_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/mkv5x_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/mpc57xx_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/mpfsxxx_eth1_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/mpfsxxx_eth2_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/msp432e4_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/nuc472_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/omapl138_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/pic32mx_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/pic32mz_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/ra6_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/rx62n_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/rx63n_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/rza1_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/s32k148_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/s5d9_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/s7g2_eth1_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/s7g2_eth2_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/sam3x_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/sam4e_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/sam7x_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/sam9263_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/sama5d2_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/sama5d3_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/sama5d3_geth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/same54_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/same70_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/samv71_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/stm32f1xx_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/stm32f2xx_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/stm32f4xx_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/stm32f7xx_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/stm32h7xx_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/stm32mp1xx_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/str912_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/tc2xx_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/tc3xx_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/tm4c129_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/tms570_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/xmc4400_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/xmc4500_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/xmc4700_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/xmc4800_eth_driver.o \
./CycloneTcp/cyclone_tcp/drivers/mac/zynq7000_eth_driver.o 

C_DEPS += \
./CycloneTcp/cyclone_tcp/drivers/mac/a2fxxxm3_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/am335x_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/aps3_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/avr32_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/efm32gg11_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/esp32_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/f28m35x_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/fm3_eth1_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/fm3_eth2_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/fm4_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/gd32f307_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/lm3s_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/lpc175x_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/lpc176x_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/lpc178x_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/lpc18xx_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/lpc23xx_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/lpc43xx_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/lpc54xxx_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/m2sxxx_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/m487_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/mcf5225x_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/mcimx6ul_eth1_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/mcimx6ul_eth2_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1020_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1050_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1060_eth1_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1060_eth2_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1170_eth1_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/mimxrt1170_eth2_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/mk6x_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/mk7x_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/mkv5x_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/mpc57xx_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/mpfsxxx_eth1_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/mpfsxxx_eth2_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/msp432e4_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/nuc472_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/omapl138_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/pic32mx_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/pic32mz_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/ra6_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/rx62n_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/rx63n_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/rza1_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/s32k148_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/s5d9_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/s7g2_eth1_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/s7g2_eth2_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/sam3x_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/sam4e_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/sam7x_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/sam9263_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/sama5d2_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/sama5d3_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/sama5d3_geth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/same54_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/same70_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/samv71_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/stm32f1xx_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/stm32f2xx_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/stm32f4xx_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/stm32f7xx_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/stm32h7xx_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/stm32mp1xx_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/str912_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/tc2xx_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/tc3xx_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/tm4c129_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/tms570_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/xmc4400_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/xmc4500_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/xmc4700_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/xmc4800_eth_driver.d \
./CycloneTcp/cyclone_tcp/drivers/mac/zynq7000_eth_driver.d 


# Each subdirectory must supply rules for building sources it contributes
CycloneTcp/cyclone_tcp/drivers/mac/%.o: ../CycloneTcp/cyclone_tcp/drivers/mac/%.c CycloneTcp/cyclone_tcp/drivers/mac/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F407xx -DGPL_LICENSE_TERMS_ACCEPTED -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/CORP.AIRTIES.COM/zafer.satilmis/STM32CubeIDE/workspace_1.7.0/evk_spi/CycloneTcp/common" -I"/home/CORP.AIRTIES.COM/zafer.satilmis/STM32CubeIDE/workspace_1.7.0/evk_spi/CycloneTcp/cyclone_tcp" -I"/home/CORP.AIRTIES.COM/zafer.satilmis/STM32CubeIDE/workspace_1.7.0/evk_spi/STM32-CycloneTCP-ENC28J60-master" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

